module.exports = {
  RECEIVE_ERRORS: "RECEIVE_ERRORS",
  RECEIVE_ITEMS: "RECEIVE_ITEMS",
  ITEM_DETAILS_FETCHED: "ITEM_DETAILS_FETCHED",
  ITEM_DESTROYED: "ITEM_DESTROYED",
  FAVORITE_ADDED: "ITEM_FAVORITE_ADDED",
  FAVORITE_REMOVED: "ITEM_FAVORITE_REMOVED"
};
