module.exports = {
  ORDER_ADDED: "ORDER_ADDED",
  ORDER_UPDATED: "ORDER_UPDATED",
  ORDER_REMOVED: "ORDER_REMOVED",
  RECEIVE_ERRORS: "RECEIVE_ORDER_ERRORS",
  CURRENT_ORDER_SET: "CURRENT_ORDER_SET"
};
