module.exports = {
  RECEIVE_ERRORS: "RECEIVE_ERRORS",
  RECEIVE_STORES: "RECEIVE_STORES",
  STORE_ADDED: "STORE_ADDED",
  STORE_DETAILS_FETCHED: "STORE_DETAILS_FETCHED",
  STORE_DESTROYED: "STORE_DESTROYED",
  FAVORITE_ADDED: "STORE_FAVORITE_ADDED",
  FAVORITE_REMOVED: "STORE_FAVORITE_REMOVED"
};
